"""recovery_tokens

Revision ID: 24d4dbf6f8d4
Revises: fca89f1b9733
Create Date: 2025-06-24 15:53:47.781842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d4dbf6f8d4'
down_revision = 'fca89f1b9733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('valid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_token'), ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Tokens_token'))

    op.drop_table('tokens')
    # ### end Alembic commands ###
